stages:
  - build
  - test
  - push
  - deploy
  - unit_tests

variables:
  DOCKER_IMAGE_NAME: yermanov/appzhardem
  DOCKER_IMAGE_TAG: latest

build:
  stage: build
  image: docker:19.03
  services:
    - docker:19.03-dind
  before_script:
    - docker login -u yermanov -p dckr_pat_WrKV3KZ4hVqY7o6WRhqIfRuueSM
  script:
    - docker build -t appzhardem-app:latest .
    - docker push appzhardem-app:latest

test:
  stage: test
  script:
    - echo "Running tests here..."

push:
  stage: push
  script:
    - echo "Pushing to registry here..."

deploy_digitalocean:
  stage: deploy
  image: alpine
  before_script:
    - apk add --update --no-cache curl
  script:
    - echo "Deploying to DigitalOcean..."
