version: '3.8'

services:
  minio:
    container_name: minio-container
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
    restart: always
    command: server /data

  app:
    image: yermanov/zhardem-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - minio
    environment:
      MINIO_URL: https://zhadem-app.onrender.com
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

