version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - minio
  minio:
    image: minio/minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
