version: '3.8'
services:

  minio:
    container_name: minio-container
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9090:9090"
      - "9000:9000"
    restart: always
    command: server -console-address :9090 /data

volumes:
  minio-data:
