version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:latest
    env_file: .env  # Также указываем на файл .env для сервиса db
    ports:
      - "5432:5432"