spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
            client-id: 609756543286-sm69ucl3n8m36ri8motg0odu0q1dpinq.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/v1/review
  datasource:
    url: jdbc:postgresql://dpg-co060u63e1ms73algvj0-a.oregon-postgres.render.com/zhardem_db_kii3
    username: zhardem_db_kii3_user
    password: ZaTPkuukn5p2Ga4NAqIcvmU7nHADzgpL
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

aws:
  accessKey: AKIAYURL6RHVHNNB72VR
  secretKey: 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
  bucketName: medicalapp
application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            access-token-expiration: 86400000 # a day
            refresh-token-expiration: 604800000 # 7 days

    time-zone: Z
paypal:
  client-id: AciClmVrEq7EwUAkQEtVE_MEQzKgINueC7S9RjRqe6NyQNreDoScKODDAOTuK9M5SDn3YEmAqkHTLDSd
  client-secret: EFpmQGIL49gtbYjmGkrrWrYU_boWKfVpsHBLjhJughLKyF1FiZHXf-7tB2hhe_akNzgkJEPEokyD_KWz
  mode: sandbox


