spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 609756543286-sm69ucl3n8m36ri8motg0odu0q1dpinq.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/api/v1/review
  datasource:
    url: "jdbc:postgresql://dpg-cnjjqmqcn0vc73c2dvdg-a.singapore-postgres.render.com:5432/zhardem_db_v6l6"
    username: "zhardem_db_v6l6_user"
    password: "dljO8MxYRiskDI48FbDjK37rXS4Wjf4i"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
minio:
  bucket-name: zhardemapp
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            access-token-expiration: 86400000 # a day
            refresh-token-expiration: 604800000 # 7 days

    time-zone: Z
