spring:
  datasource:
    url: jdbc:postgresql://dpg-cng0ptmct0pc738eh14g-a.oregon-postgres.render.com/zhardem_db
    username: zhadem_db
    password: FSiqlUNrfOv3ZV3mLmy0qmO8bfYhEey8
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
minio:
  bucket-name: zhardem_app
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            access-token-expiration: 86400000 # a day
            refresh-token-expiration: 604800000 # 7 days

    time-zone: Z